defaults: &defaults
  method: post
  local: false
  skip_default_ids: false
defaults_on: &defaults_on
  :label: true
  :offset: true
  :wrap_all: true
  :wrap_input: true
  :wrap_checkbox: true
  :wrap_checkboxes: true
  :wrap_radio: true
  :wrap_radios: true
  :wrap_submit: false
  :autocomplete: true
  :placeholder: true
  :autofilter: false
default:
  <<: *defaults
  
  on:
    <<: *defaults_on
    wrap_submit: false
    autocomplete: true
    placeholder: false
  :css:
    :form: ui form
    :wrap_all: inline fields
    :wrap_all_error: inline error fields
    :wrap_all_required: inline required fields
    :label: six wide field
    :offset: six wide field
    :help_icon: grey question circle icon
    :wrap_input: six wide field
    :wrap_short_input: three wide field
    :select: ui fluid search dropdown
    :multi_select: ui fluid search dropdown
    :checkbox: hidden
    :wrap_checkbox: ui toggle checkbox
    :wrap_checkboxes: six wide field ui labels
    :inline_checkbox: ui label checkbox
    :inline_checkbox_checked: ui teal label checkbox
    :wrap_radios: six wide field ui labels
    :inline_radio: ui label radio checkbox
    :inline_radio_checked: ui teal label radio checkbox
    :submit: ui blue button
search:
  <<: *defaults
  :method: get
  :skip_default_ids: true
  :on:
    <<: *defaults_on
    :wrap_all: false
    :label: false
    :offset: false
    :autocomplete: true
    :placeholder: true
    :autofilter: true
  :css:
    :form: ui form
    :wrap_input: field
    :wrap_short_input: field
    :wrap_checkbox: ui toggle checkbox
    :wrap_checkboxes: six wide field ui labels
    :inline_checkbox: ui label checkbox
    :inline_checkbox_checked: ui teal label checkbox
    :radio: hidden
    :wrap_radio: ui radio checkbox
    :wrap_radios: six wide field ui labels
    :inline_radio: ui label radio checkbox
    :inline_radio_checked: ui teal label radio checkbox
    :wrap_submit: field
    :submit: ui blue button
weui:
  <<: *defaults
  :on:
    <<: *defaults_on
  :css:
    :form: weui-cells weui-cells_form
    :wrap_all: weui-cell
    :wrap_all_error: inline field error
    :wrap_input: weui-cell__bd
    :wrap_submit: weui-btn-area
    :label: weui-label
    :cinput: weui-input
    :select: weui-select
    :muilti_select: weui-select
    :submit: weui-btn weui-btn_primary
bootstrap_form:
  <<: *defaults
  :on:
    <<: *defaults_on
    :offset: false
  :css:
    :form: form-horizontal
    :wrap_all: form-group
    :wrap_all_error: form-group has-error
    :label: col-sm-2 control-label
    :wrap_input: col-sm-10
    :input: form-control
    :checkbox: checkbox
    :wrap_checkbox: checkbox-inline
    :inline_checkbox_checked: checkbox-inline
    :wrapper_submit: col-sm-offset-2 col-sm-10
    :submit: btn btn-default
bootstrap_search_form:
  <<: *defaults
  :on:
    <<: *defaults_on
    wrapper_input: false
    wrapper_submit: false
    offset: false
  :css:
    :form: form-inline
    :wrapper_all: from-group
    :wrapper_input: col-sm-10
    :wrapper_submit: col-sm-offset-2 col-sm-10
    :label: sr-only
    :input: form-control
    :checkbox: checkbox
    :submit: btn btn-default
    :wrapper_checkbox_checked: checkbox-inline
    :wrapper_checkbox: checkbox-inline
